'use strict';

const js = require('@eslint/js');
const { fixupPluginRules } = require('@eslint/compat');
const tsParser = require('@typescript-eslint/parser');
const tsPlugin = require('@typescript-eslint/eslint-plugin');
const reactPluginRaw = require('eslint-plugin-react');
const reactNativePluginRaw = require('eslint-plugin-react-native');
const bookkeeprrPlugin = require('eslint-plugin-bookkeeprr-mobile');
const globals = require('globals');

// `eslint-plugin-react@7.37.5` and `eslint-plugin-react-native@5.0.0` were
// authored against ESLint v8 and call legacy context APIs (`getFilename`,
// `getSourceCode`, etc.) that were removed in ESLint v10. `fixupPluginRules`
// wraps each rule so those calls are re-derived from the v10 context.
const reactPlugin = fixupPluginRules(reactPluginRaw);
const reactNativePlugin = fixupPluginRules(reactNativePluginRaw);

// `eslint-plugin-react-native` only ships a legacy `all` config, so mirror its
// rule set inline here. The list is taken from
// `require('eslint-plugin-react-native').configs.all.rules`.
const reactNativeAllRules = {
  'react-native/no-unused-styles': 'error',
  'react-native/no-inline-styles': 'error',
  'react-native/no-color-literals': 'error',
  'react-native/sort-styles': 'error',
  'react-native/split-platform-components': 'error',
  'react-native/no-raw-text': 'error',
  'react-native/no-single-element-style-arrays': 'error',
};

const projectRules = {
  'react/react-in-jsx-scope': 'off',
  'react/prop-types': 'off',
  'react-native/no-inline-styles': 'off',
  'react-native/no-raw-text': 'off',
  'react-native/sort-styles': 'off',
  '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
  'bookkeeprr-mobile/no-color-literals': 'error',
};

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'ios/**',
      'android/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'docs/**',
      // The foliate-js WebView bundle is generated by esbuild (DO NOT EDIT).
      'src/features/reader/generated/**',
    ],
  },
  js.configs.recommended,
  ...tsPlugin.configs['flat/recommended'],
  {
    files: ['**/*.{js,jsx,ts,tsx,mjs,cjs}'],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2022,
      },
    },
    plugins: {
      react: reactPlugin,
      'react-native': reactNativePlugin,
      'bookkeeprr-mobile': bookkeeprrPlugin,
    },
    settings: {
      // eslint-plugin-react@7.37.5 calls `context.getFilename()` when it tries
      // to detect React's version, but that method was removed in ESLint v10.
      // Pin the version explicitly to skip the detection code path.
      react: { version: '19.2' },
    },
    rules: {
      ...reactPluginRaw.configs.flat.recommended.rules,
      ...reactNativeAllRules,
      ...projectRules,
    },
  },
  {
    files: ['tests/**/*', '**/*.test.ts', '**/*.test.tsx'],
    rules: {
      'bookkeeprr-mobile/no-color-literals': 'off',
    },
  },
  {
    files: ['src/theme/**/*'],
    rules: {
      'bookkeeprr-mobile/no-color-literals': 'off',
    },
  },
  {
    files: [
      'tools/**/*.js',
      '**/*.cjs',
      'jest.config.js',
      'eslint.config.js',
      'metro.config.js',
      'babel.config.js',
      'tests/mocks/**/*.js',
    ],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
        ...globals.commonjs,
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
];
